=== nambach/XmlSyntaxChecker/src/main/resources/static/xsd/crawling.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           targetNamespace="http://nambm.io/crawling-rule"
           xmlns="http://nambm.io/crawling-rule"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="rules" type="rules"/>

  <xs:complexType name="rules">
    <xs:sequence>
      <xs:element type="rule" name="rule" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="rule">
    <xs:all>
      <xs:element type="xs:string" name="siteName"/>
      <xs:element type="xs:string" name="basedUrl"/>
      <xs:element type="topicList" name="topics"/>
      <xs:element type="xs:string" name="collectionXpath"/>
      <xs:element type="item" name="item"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="topicList">
    <xs:sequence>
      <xs:element type="topicType" name="topic" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="topicType">
    <xs:all>
      <xs:element type="xs:string" name="topicName"/>
      <xs:element type="xs:string" name="topicCode"/>
      <xs:element type="urlType" name="url"/>
      <xs:element type="xs:string" name="fragmentXpath"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="urlType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="incrementParam" type="xs:string" default=""/>
        <xs:attribute name="from" type="xs:string" default="1"/>
        <xs:attribute name="to" type="xs:string" default="1"/>
        <xs:attribute name="step" type="xs:string" default="1"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="item">
    <xs:sequence>
      <xs:element type="itemDetail" name="detailXpath" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="itemDetail">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="detailName" type="xs:string"/>
        <xs:attribute name="prefix" type="xs:string" default=""/>
        <xs:attribute name="postfix" type="xs:string" default=""/>
        <xs:attribute name="isRequired" type="xs:boolean" default="false"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== nambach/XmlSyntaxChecker/src/main/resources/static/xml/book-rule.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://nambm.io/crawling-rule"
       xsi:schemaLocation="http://nambm.io/crawling-rule ../xsd/crawling.xsd">

                  Vinabook</siteName>
        <basedUrl>https://www.vinabook.com/


                      Sách vừa phát hành trong tuần</topicName>
                       newArr</topicCode>
                <url incrementParam="?page={i}" to="5">https://www.vinabook.com/sach-moi-phat-hanh</url>
                <fragmentXpath>//table[contains(@class, "template-products")]
            </topic>

                           Kho Sách Giảm Giá</topicName>
                <topicCode>sale</topicCode>
                <url incrementParam="?page={i}" to="5">https://www.vinabook.com/kho-sach-giam-gia</url>
                <fragmentXpath>//table[contains(@class, "template-products")]</fragmentXpath>
            </topic>
        </topics>
        <collectionXpath>*//td[contains(@class, "compact")]</collectionXpath>
        <item>
            <detailXpath detailName="id" prefix="VNB_" isRequired="true">/@value</detailXpath>
            *//a[contains(@class, "product-title")]/text()</detailXpath>
    </rule>
</rules>
